/**
 * What goes into a software statement, and when Muster refuses to make one.
 *
 * This module is the whole of the vouching decision, and it is pure on purpose. A
 * software statement is Muster telling a stranger's authorization server "register this
 * client, I vouch for the metadata" - so what the claim set says and who is allowed to
 * cause one to exist are the two most security-critical judgements in the codebase, and
 * both are decided here where they can be exhausted by unit tests with no database, no
 * network and no clock of their own (constitution principle II).
 *
 * Four decisions are worth stating.
 *
 * **The claim names come from the contract, not from convenience.**
 * `contracts/registration-profile.md` is a vendor-facing contract that Signet's
 * `002-trusted-dcr-tickets` implements against, so the claim vocabulary is centralised in
 * {@link buildSoftwareStatementClaims} and nowhere else. Renaming a claim is a breaking
 * change to somebody else's product.
 *
 * **The expiry is capped, not validated.** FR-023 requires an expiry no later than the
 * event's end plus the event's configured grace period, and the way to guarantee that is
 * to compute it rather than to check a number somebody supplied.
 * {@link vouchingExpirySeconds} derives it from the event alone, so there is no path by
 * which a longer one could be requested.
 *
 * **Refusal is the default.** {@link softwareStatementRefusal} answers "may this
 * statement exist?" by requiring every one of seven things to hold, in the order the
 * person can act on. A new reason to refuse is added here and is then enforced on every
 * route that mints, because there is only one place that decides.
 *
 * **The metadata is the pairing's snapshot.** Not the client's record as it stands now:
 * the snapshot is what the two parties negotiated (`data-model.md`), and an entry edited
 * after the request must not silently change what Muster vouches for.
 *
 * Author: John Grimes
 */

import { writeRefusal } from "../accounts/rules.js";
import { registrationFieldRefusal } from "../pairing/registrationFields.js";
import { canTransition } from "../pairing/stateMachine.js";

import type { AccountStanding } from "../accounts/rules.js";
import type { WriteRefusal } from "../accounts/rules.js";
import type { EventStatus } from "../events/rules.js";
import type { RegistrationFieldRefusal } from "../pairing/registrationFields.js";
import type { RegistrationFields } from "../pairing/registrationFields.js";
import type {
  PairingState,
  RegistrationMode,
} from "../pairing/stateMachine.js";

/** The algorithm every Muster-signed artefact uses. */
export const SOFTWARE_STATEMENT_ALGORITHM = "ES256";

/**
 * The claim set of a software statement.
 *
 * Exactly the claims `contracts/registration-profile.md` tabulates, spelled as the
 * contract spells them - snake_case, because they are OAuth client metadata rather than
 * TypeScript fields.
 *
 * A type alias rather than an interface, deliberately: TypeScript gives an alias an
 * implicit index signature and an interface none, and the signing helper takes the claim
 * set as a bag of JWT claims because it signs tickets with the same code.
 */
export type SoftwareStatementClaims = {
  /** The trust anchor's issuer identifier: Muster's public URL. */
  readonly iss: string;
  /** Muster's identifier for the client system. */
  readonly sub: string;
  /** The same value as {@link SoftwareStatementClaims.sub}, under RFC 7591's name. */
  readonly software_id: string;
  /** Unique statement identifier. Single registration use. */
  readonly jti: string;
  readonly iat: number;
  /** The vouching expiry: never later than event end plus the event's grace period. */
  readonly exp: number;
  /** The event slug the vouching is scoped to. */
  readonly muster_event: string;
  readonly client_name: string;
  readonly redirect_uris: readonly string[];
  readonly grant_types: readonly string[];
  readonly token_endpoint_auth_method: string;
  /** Space-separated requested scopes. */
  readonly scope: string;
  /** The app's launch URL, for servers that launch apps. */
  readonly smart_launch_url: string;
};

/** What the claim builder needs. */
export interface SoftwareStatementInput {
  /** The trust anchor's issuer identifier. Derived from `MUSTER_PUBLIC_URL`. */
  readonly issuer: string;
  /** Muster's identifier for the client system. */
  readonly softwareId: string;
  /** The statement identifier. Generated by the caller, which owns the randomness. */
  readonly jti: string;
  readonly eventSlug: string;
  /** The event's last day, as `YYYY-MM-DD`. */
  readonly eventEndsOn: string;
  /** Days past the event's last day that the vouching may still hold. */
  readonly graceDays: number;
  /** The pairing's registration snapshot. */
  readonly fields: RegistrationFields;
  readonly now: Date;
}

/** Why Muster will not mint a statement. */
export type SoftwareStatementRefusal =
  | WriteRefusal
  | "not_the_app_owner"
  | "event_not_open"
  | "pairing_not_open"
  | "not_trusted_dcr"
  | "no_registration_endpoint"
  | "vouching_window_closed"
  | RegistrationFieldRefusal;

/** What the refusal rules read off the request. */
export interface SoftwareStatementRequest {
  readonly standing: AccountStanding;
  /** Whether one of the caller's organisations owns the client side of the pairing. */
  readonly ownsClientSide: boolean;
  readonly eventStatus: EventStatus;
  readonly eventEndsOn: string;
  readonly graceDays: number;
  readonly pairingState: PairingState;
  readonly serverRegistrationMode: RegistrationMode;
  /** The address statements are presented to. Null when the entry declares none. */
  readonly registrationEndpoint: string | null;
  readonly fields: RegistrationFields;
  readonly now: Date;
}

/** Milliseconds in a day. */
const DAY_MS = 86_400_000;

/**
 * When the vouching stops (FR-023).
 *
 * The end of the event's last day, plus the event's whole grace days. `endsOn` names a
 * day rather than an instant, so "event end" is the moment that day finishes - which is
 * why the arithmetic adds one day more than the grace: an event ending on the 19th with
 * a grace of 7 vouches until midnight beginning the 27th, so the whole of the 26th is
 * still covered.
 *
 * UTC throughout. A connectathon spans time zones and a deadline that moved with the
 * server's offset would be a different deadline for each participant reading it.
 *
 * @param endsOn - The event's last day, as `YYYY-MM-DD`.
 * @param graceDays - Whole days of grace past that day.
 * @returns The expiry, as seconds since the epoch.
 * @throws {Error} When `endsOn` is not a date Muster could have stored.
 * @example
 * ```ts
 * vouchingExpirySeconds("2026-09-19", 7); // 2026-09-27T00:00:00Z
 * ```
 */
export function vouchingExpirySeconds(
  endsOn: string,
  graceDays: number,
): number {
  const day = Date.parse(`${endsOn}T00:00:00.000Z`);
  if (Number.isNaN(day)) {
    throw new TypeError(
      `an event's endsOn must be a calendar date, got "${endsOn}"`,
    );
  }
  return Math.floor((day + (graceDays + 1) * DAY_MS) / 1000);
}

/**
 * The grant types the client's snapshot implies.
 *
 * `authorization_code` always: a SMART app launch is an authorization code flow, and a
 * client registered without it could not complete one. `refresh_token` follows the
 * requested scopes, because SMART spells "I want a refresh token" as `offline_access` or
 * `online_access` and asserting the grant without the scope - or the scope without the
 * grant - would make the two halves of the same request disagree.
 *
 * @param scopes - The requested scopes.
 * @returns The grant types, `authorization_code` first.
 * @example
 * ```ts
 * grantTypesFor(["launch", "offline_access"]); // ["authorization_code", "refresh_token"]
 * ```
 */
export function grantTypesFor(scopes: readonly string[]): readonly string[] {
  const wantsRefresh = scopes.some(
    (scope) => scope === "offline_access" || scope === "online_access",
  );
  return wantsRefresh
    ? ["authorization_code", "refresh_token"]
    : ["authorization_code"];
}

/**
 * How the client authenticates at the token endpoint.
 *
 * A public client authenticates with nothing, which OAuth spells `none`. A confidential
 * one is registered for `client_secret_basic`, because that is the method whose
 * credential the server hands back at registration and which FR-026 has Muster relay
 * exactly once. `private_key_jwt` is the profile's other confidential option and is not
 * offered: the registration field set carries no public key or JWKS address for a server
 * to verify an assertion against, so asserting it would register a client that could
 * never authenticate.
 *
 * @param confidentiality - Whether the client can keep a secret.
 * @returns The `token_endpoint_auth_method` claim value.
 */
export function tokenEndpointAuthMethodFor(
  confidentiality: RegistrationFields["confidentiality"],
): string {
  return confidentiality === "confidential" ? "client_secret_basic" : "none";
}

/**
 * The claim set Muster signs (FR-023, scenario 1).
 *
 * @param input - The anchor's identity, the event, the snapshot, the statement
 *   identifier and the time. Every one of them is passed in: this function reads no
 *   clock and generates no identifier.
 * @returns The claims, ready to sign.
 * @throws {Error} When the event's end date is unparseable.
 * @example
 * ```ts
 * const claims = buildSoftwareStatementClaims({
 *   issuer: config.publicUrl,
 *   softwareId: client.system.id,
 *   jti: crypto.randomUUID(),
 *   eventSlug: event.slug,
 *   eventEndsOn: event.endsOn,
 *   graceDays: event.graceDays,
 *   fields: pairing.registrationFields,
 *   now: context.clock(),
 * });
 * ```
 */
export function buildSoftwareStatementClaims(
  input: SoftwareStatementInput,
): SoftwareStatementClaims {
  return {
    iss: input.issuer,
    sub: input.softwareId,
    software_id: input.softwareId,
    jti: input.jti,
    iat: Math.floor(input.now.getTime() / 1000),
    exp: vouchingExpirySeconds(input.eventEndsOn, input.graceDays),
    muster_event: input.eventSlug,
    client_name: input.fields.clientName.trim(),
    redirect_uris: [...input.fields.redirectUris],
    grant_types: grantTypesFor(input.fields.scopes),
    token_endpoint_auth_method: tokenEndpointAuthMethodFor(
      input.fields.confidentiality,
    ),
    scope: input.fields.scopes.join(" "),
    smart_launch_url: input.fields.launchUrl,
  };
}

/**
 * Whether a trusted-DCR run may be attempted against a pairing in this state.
 *
 * Derived from the transition table rather than restated, so the states a run accepts
 * cannot drift from the transitions the state machine admits. A `requested` pairing may
 * fail; a `failed` one may be re-requested (the retry); a fulfilled, declined or lapsed
 * one may do neither.
 *
 * @param state - The pairing's state.
 * @returns `true` when a run may be attempted.
 * @example
 * ```ts
 * dcrRunAdmissible("failed"); // true - the retry
 * ```
 */
export function dcrRunAdmissible(state: PairingState): boolean {
  return canTransition(state, "failed") || canTransition(state, "requested");
}

/**
 * Why Muster will not mint this statement, or `undefined` when it will (FR-025).
 *
 * Deny by default: every one of the seven conditions must hold. The order is the order
 * the person can act on - nothing about a revoked account is fixed by editing a redirect
 * URI, and nothing about a closed event is fixed by anything at all.
 *
 * @param request - The caller's standing, the pairing, the event and the snapshot.
 * @returns The refusal code, or `undefined` when the statement may be minted.
 * @example
 * ```ts
 * const refusal = softwareStatementRefusal({
 *   standing: account,
 *   ownsClientSide: sides.includes("client"),
 *   eventStatus: row.event.status,
 *   eventEndsOn: row.event.endsOn,
 *   graceDays: row.event.graceDays,
 *   pairingState: row.pairing.state,
 *   serverRegistrationMode: profile.registrationMode,
 *   registrationEndpoint: profile.registrationEndpoint,
 *   fields: row.pairing.registrationFields,
 *   now: context.clock(),
 * });
 * ```
 */
export function softwareStatementRefusal(
  request: SoftwareStatementRequest,
): SoftwareStatementRefusal | undefined {
  const standing = writeRefusal(request.standing);
  if (standing !== undefined) {
    // Scenario 4: a revoked member gets no statement, whatever else is true.
    return standing;
  }
  if (!request.ownsClientSide) {
    // FR-025: the client must belong to an organisation of the requesting member.
    return "not_the_app_owner";
  }
  if (request.eventStatus !== "open") {
    return "event_not_open";
  }
  if (!dcrRunAdmissible(request.pairingState)) {
    return "pairing_not_open";
  }
  if (request.serverRegistrationMode !== "trustedDcr") {
    return "not_trusted_dcr";
  }
  if (
    request.registrationEndpoint === null ||
    request.registrationEndpoint.trim().length === 0
  ) {
    return "no_registration_endpoint";
  }
  if (
    vouchingExpirySeconds(request.eventEndsOn, request.graceDays) * 1000 <=
    request.now.getTime()
  ) {
    // An event whose grace has run out can vouch for nothing: the statement would be
    // expired at the moment it was signed.
    return "vouching_window_closed";
  }
  // Last, because it is the one a person fixes by editing the request.
  return registrationFieldRefusal(request.fields);
}
