/**
 * Zod schemas shared by the server and the web console.
 *
 * The HTTP contract in `contracts/http-api.md` is expressed here so that one
 * definition validates requests on the server and types responses in the
 * browser.
 *
 * @author John Grimes
 */

export {
  capabilityHighlightsSchema,
  checkResultSchema,
  checkStatusSchema,
  discoveryHighlightsSchema,
  driftFlagSchema,
  scopeWarningSchema,
  type CapabilityHighlights,
  type CheckResult,
  type CheckStatus,
  type DiscoveryHighlights,
  type DriftFlag,
  type ScopeWarning,
} from "./checks.ts";
export {
  accountStatusSchema,
  authorizationModeSchema,
  checkFailureModeSchema,
  coverageOutcomeSchema,
  errorEnvelopeSchema,
  eventStatusSchema,
  harnessCheckOutcomeSchema,
  harnessVerdictSchema,
  pageSchema,
  paginationSchema,
  pairingStateSchema,
  registrationModeSchema,
  signingKeyStatusSchema,
  signingPurposeSchema,
  type AccountStatus,
  type AuthorizationMode,
  type CheckFailureMode,
  type CoverageOutcome,
  type ErrorEnvelope,
  type EventStatus,
  type HarnessCheckOutcome,
  type HarnessVerdict,
  type Pagination,
  type PairingState,
  type RegistrationMode,
  type SigningKeyStatus,
  type SigningPurpose,
} from "./common.ts";
export {
  accountResponseSchema,
  accountsResponseSchema,
  accountViewSchema,
  addMemberRequestSchema,
  clientConfidentialitySchema,
  clientProfileSchema,
  contactSchema,
  createEnrolmentRequestSchema,
  createEventRequestSchema,
  createOrganisationRequestSchema,
  createSystemRequestSchema,
  daySchema,
  emailSchema,
  enrolledSystemSchema,
  enrolmentResponseSchema,
  enrolmentViewSchema,
  eventDetailSchema,
  eventResponseSchema,
  eventsResponseSchema,
  eventSummarySchema,
  eventSystemSchema,
  eventSystemsSchema,
  contactsResponseSchema,
  membershipSchema,
  organisationResponseSchema,
  organisationSummarySchema,
  serverProfileSchema,
  sessionViewSchema,
  signInRequestSchema,
  signUpRequestSchema,
  systemKinds,
  systemKindSchema,
  systemRecordSchema,
  systemResponseSchema,
  systemsResponseSchema,
  updateEventRequestSchema,
  updateSystemRequestSchema,
  verifyRequestSchema,
  type AccountView,
  type AddMemberRequest,
  type ClientConfidentiality,
  type ClientProfile,
  type Contact,
  type CreateEnrolmentRequest,
  type CreateEventRequest,
  type CreateOrganisationRequest,
  type CreateSystemRequest,
  type EnrolledSystem,
  type EnrolmentView,
  type EventDetail,
  type EventSummary,
  type EventSystem,
  type EventSystems,
  type Membership,
  type OrganisationSummary,
  type ServerProfile,
  type SessionView,
  type SignInRequest,
  type SignUpRequest,
  type SystemKind,
  type SystemRecord,
  type UpdateEventRequest,
  type UpdateSystemRequest,
} from "./directory.ts";
export {
  createPairingRequestSchema,
  declinePairingRequestSchema,
  fulfilPairingRequestSchema,
  pairingConflictSchema,
  pairingDetailSchema,
  pairingEventDetailSchema,
  pairingEventSchema,
  pairingPartySchema,
  pairingResponseSchema,
  pairingsResponseSchema,
  pairingSideSchema,
  pairingSummarySchema,
  registrationFieldsSchema,
  type CreatePairingRequest,
  type DeclinePairingRequest,
  type FulfilPairingRequest,
  type PairingConflict,
  type PairingDetail,
  type PairingEvent,
  type PairingEventDetail,
  type PairingParty,
  type PairingSide,
  type PairingSummary,
  type RegistrationFields,
} from "./pairings.ts";
export {
  dcrRunStepSchema,
  dcrStepOutcomeSchema,
  jwksSchema,
  publicJwkSchema,
  registrationErrorSchema,
  softwareStatementViewSchema,
  statementClaimsSchema,
  type DcrRunStep,
  type DcrStepOutcome,
  type Jwks,
  type PublicJwk,
  type RegistrationError,
  type SoftwareStatementView,
  type StatementClaims,
} from "./registration.ts";
