/**
 * Zod schemas shared by the server and the web console.
 *
 * The HTTP contract in `contracts/http-api.md` is expressed here so that one
 * definition validates requests on the server and types responses in the
 * browser.
 *
 * @author John Grimes
 */

export {
  accountStatusSchema,
  authorizationModeSchema,
  checkFailureModeSchema,
  coverageOutcomeSchema,
  errorEnvelopeSchema,
  eventStatusSchema,
  harnessCheckOutcomeSchema,
  harnessVerdictSchema,
  pageSchema,
  paginationSchema,
  pairingStateSchema,
  registrationModeSchema,
  type AccountStatus,
  type AuthorizationMode,
  type CheckFailureMode,
  type CoverageOutcome,
  type ErrorEnvelope,
  type EventStatus,
  type HarnessCheckOutcome,
  type HarnessVerdict,
  type Pagination,
  type PairingState,
  type RegistrationMode,
} from "./common.ts";
export {
  accountViewSchema,
  addMemberRequestSchema,
  clientConfidentialitySchema,
  clientProfileSchema,
  contactSchema,
  createEnrolmentRequestSchema,
  createEventRequestSchema,
  createOrganisationRequestSchema,
  createSystemRequestSchema,
  daySchema,
  emailSchema,
  enrolledSystemSchema,
  enrolmentViewSchema,
  eventDetailSchema,
  eventSummarySchema,
  eventSystemsSchema,
  membershipSchema,
  organisationSummarySchema,
  serverProfileSchema,
  sessionViewSchema,
  signInRequestSchema,
  signUpRequestSchema,
  systemKinds,
  systemKindSchema,
  systemRecordSchema,
  updateEventRequestSchema,
  updateSystemRequestSchema,
  verifyRequestSchema,
  type AccountView,
  type AddMemberRequest,
  type ClientConfidentiality,
  type ClientProfile,
  type Contact,
  type CreateEnrolmentRequest,
  type CreateEventRequest,
  type CreateOrganisationRequest,
  type CreateSystemRequest,
  type EnrolledSystem,
  type EnrolmentView,
  type EventDetail,
  type EventSummary,
  type EventSystems,
  type Membership,
  type OrganisationSummary,
  type ServerProfile,
  type SessionView,
  type SignInRequest,
  type SignUpRequest,
  type SystemKind,
  type SystemRecord,
  type UpdateEventRequest,
  type UpdateSystemRequest,
} from "./directory.ts";
